### ISSUE TITLE
petsc does not compile with MPI > 3.0

### ISSUE THREAD

**Issue by Antoine948398** [GEOS-DEV/thirdPartyLibs#57]
Hello,

It seems that PETSc use functions that are not supported anymore in MPI v4.0.1

```
/home/amazuyer/devel/geosx/thirdPartyLibs/build-default-clang-release/petsc/src/petsc/src/sys/objects/init.c: In function ‘PetscOptionsCheckInitial_Private’:
/home/amazuyer/devel/geosx/thirdPartyLibs/build-default-clang-release/petsc/src/petsc/src/sys/objects/init.c:417:40: error: ‘MPI_Handler_function’ undeclared (first use in this function); did you mean ‘MPI_User_function’?
  417 |     ierr = MPI_Comm_create_errhandler((MPI_Handler_function*)Petsc_MPI_DebuggerOnError,&err_handler);CHKERRQ(ierr);
      |                                        ^~~~~~~~~~~~~~~~~~~~
      |   
```

Indeed, according to this comment:

https://github.com/open-mpi/ompi/blob/c672a51ccd09c7c0b208c912101e46ce391ab1e7/ompi/include/mpi.h.in#L2753

It does not exist anymore
